platform:ios, '8.0'
use_frameworks!

target 'GJImageCarousel' do
pod 'Alamofire', '~> 4.4.0'
pod 'SnapKit', '~> 3.2.0'
pod 'SwiftyJSON', '~> 3.1.4'
pod 'SwiftyUserDefaults', '~> 3.0.0'
pod 'ObjectMapper', '~> 2.2.4'
pod 'Kingfisher', '~> 3.5.0'
end
